# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_time',
        ),
    ]
